swagger: '2.0'
info:
  title: projectApi
  description: Intake Project
  version: 1.0.0
host: mybluemix.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /projects:
    get:
      summary: List Projects
      description: List of all projects
      parameters:
        - name: name
          in: query
          description: Name of User to filter (TBD Submitted vs logged in).
          required: false
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Projects
      responses:
        '200':
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add a Project
      description: Add a project to persist in data store
      parameters:
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Projects
      responses:
        '200':
          description: Standard http codes
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /projects/id:
    get:
      summary: Project Details by id
      description: |
        The project details will be listed by id
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific project. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - ProjectDetails
      responses:
        '200':
          description: Project details for a given project
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update a project passing using an ID
      description: |
        Update a project passing using an ID
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific project. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - ProjectDetails
      responses:
        '200':
          description: Standard http code
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /services:
    get:
      summary: List Services
      description: List of all services
      parameters:
        - name: group
          in: query
          description: Group name of Service
          required: false
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Services
      responses:
        '200':
          description: An array of services
          schema:
            type: array
            items:
              $ref: '#/definitions/Services'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add a Service
      description: Add a service to persist in data store
      parameters:
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Services
      responses:
        '200':
          description: Standard http codes
          schema:
            type: array
            items:
              $ref: '#/definitions/Services'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /services/id:
    get:
      summary: Service Details by ID
      description: Service details will be listed by ID
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific project. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - ServiceDetails
      responses:
        '200':
          description: Service details
          schema:
            type: array
            items:
              $ref: '#/definitions/Services'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update a Service using an ID
      description: |
        Update a project passing using an ID
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific project. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - ServiceDetails
      responses:
        '200':
          description: Standard http code
          schema:
            type: array
            items:
              $ref: '#/definitions/Services'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /regions:
    get:
      summary: List Regions
      description: List of all regions
      parameters:
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Regions
      responses:
        '200':
          description: An array of regions
          schema:
            type: array
            items:
              $ref: '#/definitions/Regions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add a Region
      description: Add a region to persist in data store
      parameters:
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - Regions
      responses:
        '200':
          description: Standard http codes
          schema:
            type: array
            items:
              $ref: '#/definitions/Regions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /regions/id:
    get:
      summary: Region Details by ID
      description: Region details will be listed by ID
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific region. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - RegionDetails
      responses:
        '200':
          description: Region details
          schema:
            type: array
            items:
              $ref: '#/definitions/Regions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update a Region using an ID
      description: |
        Update a Region using an ID
      parameters:
        - name: id
          in: query
          description: >-
            Unique identifier representing a specific Region. For example,
            57d21107e6f3b43e004a0eb5.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Accesstoken.
          required: true
          type: string
      tags:
        - RegionDetails
      responses:
        '200':
          description: Standard http code
          schema:
            type: array
            items:
              $ref: '#/definitions/Regions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Project:
    type: object
    properties:
      id:
        type: string
        description: >-
          Unique identifier representing a specific project. For example,
          CDTS001114.
      name:
        type: string
        description: Name of project.
      priority:
        type: string
        description: project priority.
      fundingApproved:
        type: string
        description: 'Is funding approved {yes/no/pending}'
      requestorName:
        type: string
        description: Name of person requesting the project.
      requestorEmail:
        type: string
        description: Email address of person requesting the project.
      submittedDate:
        type: string
        description: Intake date of project.
      details:
        type: array
        items:
          $ref: '#/definitions/ProjectDetails'
      assessment:
        type: array
        items:
          $ref: '#/definitions/ProjectAssessment'
      comments:
        type: array
        items:
          $ref: '#/definitions/ProjectComments'
  ProjectDetails:
    type: object
    properties:
      anticipatedBudget:
        type: string
        description: anticipated budget
      requestedStartDate:
        type: string
        description: requested start date
      requestedEndDate:
        type: string
        description: requested end date
      projectType:
        type: string
        description: 'Type of project e,g Design'
      kpaAlignedStrategicInitiative:
        type: string
        description: Strategic initiative project is aligned to. Perform/Grow/Lead
      scope:
        type: string
        description: Scope Statement for Project
      reason:
        type: string
        description: Reason or Benefit text why project is Required
      executiveSponsor:
        type: string
        description: Name of person (IT Executive)sponsoring project
      businessSponsor:
        type: string
        description: Name of person (Business Executive)sponsoring project
      applicationsImpacted:
        type: array
        items:
          $ref: '#/definitions/ApplicationsImpacted'
        description: applications impacted array
      departmentImpacted:
        type: array
        items:
          $ref: '#/definitions/DepartmentsImpacted'
        description: departments impacted array
      regionsImpacted:
        type: array
        items:
          $ref: '#/definitions/RegionsImpacted'
        description: regions array
      servicesImpacted:
        type: array
        items:
          $ref: '#/definitions/ServicesImpacted'
        description: Services array
  ProjectAssessment:
    type: object
    properties:
      emtLead:
        type: string
        description: Name of person leading EMT Team
      emtPrimaryOwner:
        type: string
        description: Name of person owing EMT
      emtTeamsImpacted:
        type: array
        items:
          $ref: '#/definitions/EMTTeamsImpacted'
        description: Services array
      projectType:
        type: string
        description: 'Type of project e.g Waterfall, Agile, Lean'
      budget:
        type: array
        items:
          $ref: '#/definitions/BudgetDetails'
        description: Budgets array
  ProjectComments:
    type: object
    properties:
      desc:
        type: string
        description: Comment Text
      commentDate:
        type: string
        description: Date of comment
        format: date
      commenter:
        type: string
        description: Name of person enteirng comment
  Services:
    type: object
    properties:
      id:
        type: string
        description: 'ID or name of service. For example, tssServices.'
      parent:
        type: string
        description: 'Parent service, null for top level element.'
  Regions:
    type: object
    properties:
      id:
        type: string
        description: >-
          Unique identifier representing a specific region. For example, West -
          county.
      name:
        type: string
        description: Region name
  ApplicationsImpacted:
    type: object
    properties:
      name:
        type: string
        description: Array of applictaion names impacted
  DepartmentsImpacted:
    type: object
    properties:
      name:
        type: string
        description: Array of applictaion names impacted
  RegionsImpacted:
    type: object
    properties:
      name:
        type: string
        description: Array of regions IDs impacted and tagged to project
  ServicesImpacted:
    type: object
    properties:
      name:
        type: string
        description: Array of Services Impacted and tagged to project. TBD
  EMTTeamsImpacted:
    type: object
    properties:
      name:
        type: string
        description: Array of EMT Team names impacted
  BudgetDetails:
    type: object
    properties:
      benefitAmount:
        type: string
        description: Benefit amount.
      benefitDescription:
        type: string
        description: Benefit Description
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
